### ISSUE TITLE
How to send server messages/commands?

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-irc#1]
It looks like there's no job for sending server messages and commands.

**Comment by silverbucket** [comment]
Yeah, I purposely left this out until we define what this should look like, how it should behave. Based on what you were thinking of doing, how would you suggest the objects look like? We can try to refine something.

**Comment by skddc** [comment]
Afaik in the IRC protocol they're also called "command". So we'd probably have a @type of "command" and define the command itseld and its parameters in one or more content properties. But I'm not as familiar with AS 2.0 as you, so I'm not sure what's possible and what isn't.

**Comment by silverbucket** [comment]
Well, first let's take a step back. Can you give me an example/list of the types of actions you want to carry out? Are these server commands, bot commands, etc. ?

**Comment by skddc** [comment]
As the issue says, any type of server message or command that's possible. See https://tools.ietf.org/html/rfc1459#section-2.3 for example. It doesn't really matter which ones we use, because any command should just be piped through and sent to the server.

**Comment by skddc** [comment]
... most important for Hyperchannel at the moment is MSG I guess, so that we can implement NickServ handling.

**Comment by skddc** [comment]
Maybe it makes sense to have both a generic command job as well as specific jobs like JOIN etc.? That way a client can implement anything without the IRC platform module specifically supporting it.

**Comment by silverbucket** [comment]
This is the kind of stuff we should avoid. I know it seems like the easiest/quickest way to get to do stuff, but the notions don't scale to other platforms and remove the benefit of the AS2.0 abstractions.

From what you've told me though, what you want to do is simply message `NickServ`, so really we should probably try to approach this using the existing paradigm of messaging someone:

```
{
  "@type": "send",
  "context": "irc",
  "actor": ...
  "target": {
    "@id": "irc://NickServ@irc.freenode.net",
    "@type": "service"
  },
  "object": {
    "@type": "message",
    "content": "identify Password1234"
  }
}
```

When we're addressing a bot/service we use the `user@host` format... and if there is a case where we need to write to the irc server directly, the id could be just `host` (do we need to do that ever?).

If we throw up more examples/use-cases we can try to shape it to suit all the different types of needs.

How does that sound to you?

**Comment by skddc** [comment]
> This is the kind of stuff we should avoid. I know it seems like the easiest/quickest way to get to do stuff, but the notions don't scale to other platforms and remove the benefit of the AS2.0 abstractions.

I disagree. It's not about the easiest way, but the way that allows us to cover 100% of server implementations, even if this module doesn't have support for the specific command yet. Also, we need *way* more commands than just messaging NickServ very soon.

> If we throw up more examples/use-cases we can try to shape it to suit all the different types of needs.
> 
> How does that sound to you?

In general I agree about special jobs, but we really need support for *all possible* IRC commands asap. The example use cases are all use cases of all IRC features. We can create issues and implement them one by one, but I don't see why we should block client development by preventing us from implementing things in the client due to concerns about semantics details. Rewriting the job object that is sent in the client software can be done in a matter of minutes.

Also, this will automatically yield the priority/order of special commands to implement, because it's just exactly what's been implemented in Hyperchannel, one by one.

Let's make our real-world app the driver of APIs and use cases!

**Comment by silverbucket** [comment]
> I disagree. It's not about the easiest way, but the way that allows us to cover 100% of server implementations, even if this module doesn't have support for the specific command yet. 

How does this limit our use-case?

> Also, we need way more commands than just messaging NickServ very soon.

Like what? (Things that this paradigm wouldn't fit) Please give me more examples.

> In general I agree about special jobs, but we really need support for all possible IRC commands asap.

What commands would not work with this kind of paradigm?

> We can create issues and implement them one by one, but I don't see why we should block client development by preventing us from implementing things in the client due to concerns about semantics details. Rewriting the job object that is sent in the client software can be done in a matter of minutes.

I'm not addressing one single use-case, to be implemented one by one. I'm taking the first use-cases as a prompting to address the issue in a scalable way.

**Comment by skddc** [comment]
MODE, LIST, INVITE, KICK, STATS are just a few examples.

**Comment by silverbucket** [comment]
Ah, OK, so, commands which apply directly to IRC, and not an extension, could be handled with the following target:

```
{
  "@type": "send",
  "context": "irc",
  "actor": {
    "@id": "foobar@irc.freenode.net"
  },
  "target": {
    "@id": "irc://irc.freenode.net",
    "@type": "service"
  },
  "object": {
    "@type": "message",
    "content": "kick asshat"
  }
}
```

We just treat everything like a DM, just instead of a person, it's a service, in this case the "base" service of just `host`, but in other cases the extension service is implied with `user@host`

**Comment by skddc** [comment]
Looks good to me.

**Comment by silverbucket** [comment]
OK, so we just need some logic which checks the URI ID, and if it has no `#room` or `user@` in the URI, it will send the message as a base `/`+`message` string.

**Comment by skddc** [comment]
Closing in favor of #4.
