### ISSUE TITLE
Unprocessed message for trying to set channel topic without op status

### ISSUE THREAD

**Issue by galfert** [sockethub/sockethub-platform-irc#19]
When trying to set the channel topic without having the right privileges, I see the following error in the sockethub console:

>sockethub-platform-irc Unprocessed message [irc://username@irc.freenode.net]:  +9s { prefix: 'verne.freenode.net',
  command: 'ERR_CHANOPRIVSNEEDED',
  params: [ 'username', '#channel', 'You\'re not a channel operator' ],
  server: 'verne.freenode.net',
  raw: ':verne.freenode.net 482 username #channel :You\'re not a channel operator',
  time: 2017-01-16T01:54:06.165Z }

**Comment by silverbucket** [comment]
I assume 'username' is an actual username, and also '#channel' is the channel. Will add checks for this.
