### ISSUE TITLE
How to change join-channel timeout?

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-irc#21]
Currently it takes 30 seconds for a channel join to fail, with an error message that tells you about the 30-second timeout. However, I couldn't find out where that is actually configured and thus how to change it to something that makes a bit more sense.

**Comment by skddc** [comment]
@silverbucket Any insight you could give maybe?

**Comment by silverbucket** [comment]
@skddc In the index.js the irc-factory module is used to create the IRC connection. Here https://github.com/sockethub/sockethub-platform-irc/blob/master/index.js#L173 you can see the timeout being set. If you have any elegant ideas for how to handle per-platform config I'm open to ideas.

**Comment by skddc** [comment]
Oh, I guess I made a mistake when searching then. Thanks.

So how about we just change it to something lower, like 10 seconds for example? Should be enough on any normal connection, as this is one is server-to-server, right?

**Comment by silverbucket** [comment]
@skddc I set it so high specifically because I was getting timeouts in some environments, so it wont really resolve the issue to just change the value (I believe it was 10 seconds originally). Hackerbeach definitely has me bumping that value :)

**Comment by skddc** [comment]
If you bumped it for Hackerbeach, then you used SH on your client machine. But that's not a usual scenario for a hosted Sockethub instance, where it would take too long to be able to tell the user that the server is not available imo.

So maybe it makes most sense if this would be a server ENV config flag actually. So you can decide based upon the environment SH is run in.

**Comment by silverbucket** [comment]
@skddc yeah that's what I mean, we need an elegant way of configuring it. ENV + config file, etc. all use the same code to gather everything up into a config object, I was wondering if you had suggestions on how the platform-specific config should look. You can view the config file example for an idea of what we have so far.

**Comment by skddc** [comment]
I guess a property with the platform name containing a platform-specific object would make sense. Maybe in a `platforms` wrapper property even. So sth like:

```json
{
  "redis": {
    "host": "redis",
    "port": 6379
  },
  "platforms": {
    "irc": {
      "connectTimeout": 10000
    }
  }
}
