### ISSUE TITLE
Connecting to a second IRC server breaks connectivity

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-irc#22]
I just merged a PR for Hyperchannel, which makes this much easier to try out yourself. When you start Hyperchannel from its `master` branch now, and you go to `/settings` (either direct or via the cog in the upper right corner), you can select a space preset to connect additional spaces. As soon as you connect one, say GIMPnet, and join a channel there, say #epiphany, you can see that it joins that channel, but when you type something in Freenode, it won't arrive there anymore.

I'm not sure if this is a general Sockethub bug or an IRC-specific one, i.e. if this would also happen if the second space were e.g. an XMPP one.

**Comment by silverbucket** [comment]
Hmm, that's not good. Will try to have a closer look soon.

**Comment by silverbucket** [comment]
@skddc does this also fail with 2 freenode separate freenode connections?

**Comment by skddc** [comment]
I haven't tried two freenodes, but that would technically still be one connection in SH, no?

**Comment by silverbucket** [comment]
@skddc The connection is determined by the URI (minus path), so irc://<username>@<host> would be a stand-alone connection.

**Comment by silverbucket** [comment]
Ah, github at my example: `irc://[username]@[host]` so if you connect to freenode twice it would be different usernames, which means different connection instance.

**Comment by skddc** [comment]
Ah, I see.

**Comment by silverbucket** [comment]
Fixed due to a scope referencing typo!

**Comment by skddc** [comment]
![party-hard](https://user-images.githubusercontent.com/842/34741314-1ff07990-f57a-11e7-964e-e4b27e88a3f5.gif)
