### ISSUE TITLE
Handle IRC server connectivity issues (via PING)

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-irc#24]
From https://github.com/67P/hyperchannel/issues/77:

> When Sockethub loses its online connection it basically doesn't know about it. It reports everything as being connected (`isConnected() called, returned true`) and doesn't reconnect after it itself regains a network connection. Sends are reported as completed during all of that, and will just not result in anything being sent to the IRC server.

http://www.livinginternet.com/r/ra_ping.htm

**Comment by silverbucket** [comment]
done in sockethub milestone v3.0
