### ISSUE TITLE
Support /me action messages

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-irc#8]
http://www.livinginternet.com/r/ra_action.htm

Currently they arrive as normal messages of type `send` without the name in front and without any indicator of being a `/me`.

**Comment by skddc** [comment]
So, my bouncer logs use a common format for action messages for this, and in the RS module I'm working on I'm combining all actions in a message type "action". There's basically no difference between a server-sent "raucao sets op on gregkare" and as user-initiated "raucao rolls on the floor laughing".

**Comment by silverbucket** [comment]
If you have debugging set and do one of these `/me` commands, does the sockethub irc platform log the raw incoming message to the console? I imagine there's something unique to `/me`'s that we can detect to update the message to indicate it.

**Comment by skddc** [comment]
I haven't looked at implementing it myself, because I'm working on other parts of Kosmos currently, but yes, there should definitely be something unique about action messages. Should be easy to implement. I added the additional information in order to help with the requirements and the format it'll use.

**Comment by skddc** [comment]
@silverbucket By the way, are you coming back on IRC sometime soon? ;)

**Comment by silverbucket** [comment]
@skddc yeah, soon, real life has gotten in the way. Been moving the past week (which was previously unplanned) and am finally starting to get things unpacked and feeling less overwhelmed. Slowly picking things back up.

**Comment by silverbucket** [comment]
This needs to be looked into for both incoming and outgoing, as it doesn't work the same with a KICK or STAT does

**Comment by silverbucket** [comment]
Can use the `Client.me` method to send `/me` messages:
https://github.com/ircanywhere/irc-factory/wiki/Setup-&-Usage

**Comment by skddc** [comment]
Ah, similarly we need basically all of the other ones in there, esp. `/notice` (for incoming notifications).

**Comment by silverbucket** [comment]
Yeah, the ones not yet added to the module are `notice`, `mode` and `ctcp`. Will open issues for each.

**Comment by silverbucket** [comment]
You can send `/me` messages like:

```
{
  "@type": "send",
  "context": "irc",
  "actor": {
    "@id": "irc://foobar@irc.freenode.net",
    "@type": "person",
    "displayName": "Foo Bar"
  },
  "object": {
    "@type": "me",
    "content": "is hungry"
  },
  "target": {
    "@id": "irc://irc.freenode.net/sockethub",
    "@type": "room",
    "displayName": "#sockethub"
  }
}
```
